-- Phase 1: Database Definition Language (DDL)
-- Creating a structured table to hold clean environmental telemetry payloads
CREATE TABLE satellite_telemetry (
    packet_id INT PRIMARY KEY,
    latitude DECIMAL(9,6) NOT NULL,
    longitude DECIMAL(9,6) NOT NULL,
    sensor_reading FLOAT NOT NULL,
    recorded_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

-- Phase 2: Data Manipulation Language (DML)
-- Simulating the ingestion of the clean logs generated by the Python script
INSERT INTO satellite_telemetry (packet_id, latitude, longitude, sensor_reading) VALUES
(101, 12.970000, 77.590000, 24.5),
(103, 12.990000, 77.610000, 26.1),
(105, 13.010000, 77.630000, 23.8);

-- Phase 3: Data Query Language (DQL) & Advanced Analytics
-- Analysis 1: Running an analytical Window Function to rank sensor readings by temperature severity
SELECT 
    packet_id,
    sensor_reading,
    ROW_NUMBER() OVER (ORDER BY sensor_reading DESC) as severity_row_num,
    RANK() OVER (ORDER BY sensor_reading DESC) as temperature_rank
FROM 
    satellite_telemetry;

-- Analysis 2: Utilizing SUM OVER to track a cumulative rolling total of incoming signal readings
SELECT 
    packet_id,
    sensor_reading,
    SUM(sensor_reading) OVER (ORDER BY packet_id) as cumulative_thermal_load
FROM 
    satellite_telemetry;
