import os

def parse_and_generate_sql(input_file="clean_telemetry.csv"):
    print("Starting Python Dynamic Ingestion Layer...")
    
    if not os.path.exists(input_file):
        print(f"Error: Target file '{input_file}' not found. Run C engine first.")
        return

    try:
        with open(input_file, "r") as file:
            lines = file.readlines()
            
        # Skip CSV column header row
        data_lines = lines[1:]
        
        print(f"Detected {len(data_lines)} data rows. Generating DML insertions:")
        print("-" * 60)
        
        for line in data_lines:
            cleaned_line = line.strip()
            
            # Skip empty trailing lines generated by systems language file markers
            if not cleaned_line:
                continue
                
            row = cleaned_line.split(",")
            packet_id, lat, lon, reading = row[0], row[1], row[2], row[3]
            
            # Enforce single quotes around packet_id to support alphanumeric text structures safely
            sql_query = f"INSERT INTO satellite_telemetry (packet_id, latitude, longitude, sensor_reading) VALUES ('{packet_id}', {lat}, {lon}, {reading});"
            print(sql_query)
            
        print("-" * 60)
        print("Data Ingestion Cycle Complete.")
        
    except IOError as e:
        print(f"System File Error: {e}")

if __name__ == "__main__":
    parse_and_generate_sql()
